<?php
namespace App\Models;

use Core\Database;
use Core\Cache;
use PDO;

class Backup
{
    private PDO $db;

    public function __construct()
    {
        $this->db = Database::getInstance();
    }

    /**
     * Get statistics for all database tables.
     */
    public function getTableStats(): array
    {
        $stmt = $this->db->query("
            SELECT 
                TABLE_NAME as table_name,
                TABLE_ROWS as estimated_rows,
                DATA_LENGTH as data_bytes,
                INDEX_LENGTH as index_bytes,
                ENGINE as engine,
                UPDATE_TIME as last_updated
            FROM information_schema.TABLES
            WHERE TABLE_SCHEMA = DATABASE()
            ORDER BY TABLE_NAME ASC
        ");
        $tables = $stmt->fetchAll(PDO::FETCH_ASSOC);

        $stats = [];
        foreach ($tables as $t) {
            $tName = $t['table_name'];
            $countStmt = $this->db->query("SELECT COUNT(*) FROM `{$tName}`");
            $exactRows = (int)$countStmt->fetchColumn();

            $dataBytes = (int)$t['data_bytes'];
            $indexBytes = (int)$t['index_bytes'];
            $bytes = $dataBytes + $indexBytes;

            $stats[] = [
                'table_name'      => $tName,
                'name'            => $tName,
                'rows'            => $exactRows,
                'data_size_kb'    => round($dataBytes / 1024, 2),
                'index_size_kb'   => round($indexBytes / 1024, 2),
                'size_mb'         => round($bytes / (1024 * 1024), 3),
                'size_formatted'  => $this->formatBytes($bytes),
                'bytes'           => $bytes,
                'engine'          => $t['engine'] ?? 'InnoDB',
                'last_updated'    => $t['last_updated'] ?? '—'
            ];
        }

        return $stats;
    }

    /**
     * Export complete database data into a single structured JSON backup.
     */
    public function exportDatabase(): array
    {
        // Get all tables
        $tablesStmt = $this->db->query("SHOW TABLES");
        $tableNames = $tablesStmt->fetchAll(PDO::FETCH_COLUMN);

        $backupData = [
            'metadata' => [
                'app_name' => APP_NAME,
                'app_version' => defined('APP_VERSION') ? APP_VERSION : '1.0.0',
                'backup_version' => '1.0',
                'created_at' => date('Y-m-d H:i:s'),
                'timestamp' => time(),
                'platform' => 'GRM B2B Marketplace',
                'total_tables' => count($tableNames),
                'total_records' => 0
            ],
            'tables' => []
        ];

        $totalRecords = 0;

        foreach ($tableNames as $tableName) {
            // Exclude transient sessions table from large dumps or keep empty array
            if ($tableName === 'sessions') {
                $backupData['tables'][$tableName] = [];
                continue;
            }

            $stmt = $this->db->query("SELECT * FROM `{$tableName}`");
            $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
            $count = count($rows);

            $backupData['tables'][$tableName] = $rows;
            $totalRecords += $count;
        }

        $backupData['metadata']['total_records'] = $totalRecords;

        return $backupData;
    }

    /**
     * Restore database from an uploaded JSON or SQL backup string.
     */
    public function importDatabase(string $content): array
    {
        $content = trim($content);
        if (empty($content)) {
            throw new \Exception("Backup file is empty.");
        }

        // Try decoding as JSON backup
        $data = json_decode($content, true);

        if (json_last_error() === JSON_ERROR_NONE && is_array($data) && isset($data['tables'])) {
            return $this->importFromJson($data);
        }

        // Fallback: If raw SQL dump was uploaded
        if (str_contains($content, 'INSERT INTO') || str_contains($content, 'CREATE TABLE')) {
            return $this->importFromSql($content);
        }

        throw new \Exception("Invalid backup format. Please provide a valid JSON or SQL backup file generated by the system.");
    }

    /**
     * Import structured JSON backup with transactional rollback safety.
     */
    private function importFromJson(array $data): array
    {
        if (empty($data['tables']) || !is_array($data['tables'])) {
            throw new \Exception("Backup file contains no table data.");
        }

        $tablesData = $data['tables'];
        $restoredTables = 0;
        $restoredRecords = 0;

        // Get list of existing tables in the database
        $existingTables = $this->db->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);

        $this->db->beginTransaction();

        try {
            // 1. Temporarily disable foreign key checks for clean restore
            $this->db->exec("SET FOREIGN_KEY_CHECKS = 0;");

            foreach ($tablesData as $tableName => $rows) {
                // Ensure table exists in database and skip active sessions table
                if (!in_array($tableName, $existingTables) || $tableName === 'sessions') {
                    continue;
                }

                // Empty existing table data
                $this->db->exec("DELETE FROM `{$tableName}`;");

                if (!empty($rows) && is_array($rows)) {
                    $firstRow = reset($rows);
                    $columns = array_keys($firstRow);
                    $colList = implode(', ', array_map(fn($c) => "`{$c}`", $columns));
                    $rowPlaceholder = '(' . implode(', ', array_fill(0, count($columns), '?')) . ')';

                    // Insert in multi-row batches of 50 for ultra-fast execution
                    $batchSize = 50;
                    $batches = array_chunk($rows, $batchSize);

                    foreach ($batches as $batch) {
                        $placeholders = [];
                        $values = [];
                        foreach ($batch as $row) {
                            $placeholders[] = $rowPlaceholder;
                            foreach ($row as $val) {
                                $values[] = $val;
                            }
                        }
                        $insertSql = "INSERT INTO `{$tableName}` ({$colList}) VALUES " . implode(', ', $placeholders);
                        $stmt = $this->db->prepare($insertSql);
                        $stmt->execute($values);
                        $restoredRecords += count($batch);
                    }
                }

                $restoredTables++;
            }

            // 2. Re-enable foreign key checks
            $this->db->exec("SET FOREIGN_KEY_CHECKS = 1;");

            // 3. Invalidate Application Caches
            Cache::delete('layout_main_components');
            Cache::delete('layout_admin_navbar');
            Cache::delete('catalog_active');
            Cache::delete('setting_vendor_module_enabled');

            $this->db->commit();

            return [
                'success'               => true,
                'restored_tables'       => $restoredTables,
                'restored_tables_count' => $restoredTables,
                'restored_records'      => $restoredRecords,
                'total_rows_restored'   => $restoredRecords,
                'backup_meta'           => $data['metadata'] ?? []
            ];

        } catch (\Throwable $e) {
            $this->db->exec("SET FOREIGN_KEY_CHECKS = 1;");
            $this->db->rollBack();
            throw new \Exception("Database restore failed: " . $e->getMessage());
        }
    }

    /**
     * Import raw SQL backup.
     */
    private function importFromSql(string $sql): array
    {
        $this->db->beginTransaction();

        try {
            $this->db->exec("SET FOREIGN_KEY_CHECKS = 0;");
            
            // Execute SQL statements
            $this->db->exec($sql);

            $this->db->exec("SET FOREIGN_KEY_CHECKS = 1;");

            Cache::delete('layout_main_components');
            Cache::delete('layout_admin_navbar');
            Cache::delete('catalog_active');
            Cache::delete('setting_vendor_module_enabled');

            $this->db->commit();

            return [
                'success' => true,
                'restored_tables' => count($this->db->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN)),
                'restored_records' => 0,
                'backup_meta' => ['format' => 'Raw SQL']
            ];
        } catch (\Throwable $e) {
            $this->db->exec("SET FOREIGN_KEY_CHECKS = 1;");
            $this->db->rollBack();
            throw new \Exception("SQL execution error during restore: " . $e->getMessage());
        }
    }

    private function formatBytes(int $bytes, int $precision = 2): string
    {
        $units = ['B', 'KB', 'MB', 'GB', 'TB'];
        $bytes = max($bytes, 0);
        $pow = floor(($bytes ? log($bytes) : 0) / log(1024));
        $pow = min($pow, count($units) - 1);
        $bytes /= pow(1024, $pow);
        return round($bytes, $precision) . ' ' . $units[$pow];
    }
}
